### PR TITLE
algos: update algorithm status

### PR DESCRIPTION
**Pull request by cujomalainey**
Update status of algorithm integration

Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>

### CODE REVIEW

**Comment by cujomalainey** [comment]
@singalsu we should add tdfb to this list

**Review by lgirdwood — APPROVED** [review]
@singalsu - do you have any updates that should be added here ?

**Review by singalsu — APPROVED** [review]

**Comment by singalsu** [comment]
@lgirdwood Yes something but I'll do a separate PR. The AEC milestone is later, a mockup first, a real usable maybe 1.8? Also could add voice audio noise suppressor and direction of arrival estimation to beamformer. The TDFB name should be added to beamformer line to avoid confusion. Keyon's FFT library could be added too as significant effort though it's not a standalone component.

**Comment by deb-intel** [comment]
@lgirdwood Shall I merge this PR now?

**Comment by lgirdwood** [comment]
> @lgirdwood Shall I merge this PR now?

Yes please.

**Pull request merged**
