### PR TITLE
Grammar/style updates to VirIO doc; PR 155

### PR DESCRIPTION
**Pull request by deb-intel**
Signed-off-by: Deb Taylor <deb.taylor@intel.com>

### CODE REVIEW

**Comment by deb-intel** [comment]
This PR does the following:
--changed virtualisation/initialisation to virtualization/initialization in order to comply with Intel's American English spelling policy. This includes filename changes: developer_guides/virtualization/virtualization.rst.
--grammar and style edits to virtualization.rst
--updated pictures in /virtualization/images. I resized all three and added borders. They appear more cleanly on the page. 

Reference: PR 155.

**Comment by lyakh** [comment]
@deb-intel thanks for updating this. But I have one request: could we wrap all lines at 80 characters? We can do that automatically. That would make it easier to work with the sources in a variety of editors and also to track back changes to the original document.

**Comment by deb-intel** [comment]
@lyakh Yes, of course! My editor is set for 78-80 lines but somehow it changes. I will chat with one of my colleagues about this today and make sure it's properly wrapped.

**Comment by deb-intel** [comment]
@lyakh  Word wrap is corrected in PR #167.

**Pull request merged**
