### PR TITLE
Probes update

### PR DESCRIPTION
**Pull request by jsarha**
Validity of these updates depend on this pull request being accepted:
https://github.com/thesofproject/sof/pull/6364

### CODE REVIEW

**Comment by jsarha** [comment]
@lgirdwood  here is the sof-docs update you were missing.

**Comment by deb-intel** [comment]
@jsarha Two warnings on line 30 and line 33 under **Build and Deploy** are causing your build to fail. The file on line 33 no longer exists (I removed it in a recent PR). Line 30 has been corrected in one of my recent PRs as well. Please be sure to do whatever necessary updates so we can merge your build.

**Comment by jsarha** [comment]
Rebased and updated the content according to changes requested to https://github.com/thesofproject/sof/pull/6364

**Review by lgirdwood — APPROVED** [review]
@deb-intel technical side is fine, pls merge when you are happy

**Review by deb-intel — APPROVED** [review]
Looks good. I will make a few grammatical edits in a separate PR.

**Pull request merged**
