### PR TITLE
Algorithms: Update processing summary table

### PR DESCRIPTION
**Pull request by singalsu**
This patch updates the component list in the table to match
current SOF git master version adds more verbose descriptions.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by deb-intel** [comment]
@singalsu @lgirdwood I can edit/merge this request if you have received all feedback.

**Comment by lgirdwood** [comment]
@deb-intel please do.

**Comment by lgirdwood** [comment]
@dgreid @cujomalainey @dbaluta @lbetlej fyi - please add any processing you guys are working on or are planning here once the initial table is merged. We can use this as the entry point for all processing docs.
@singalsu can you also add your beamformer and any other items you have planned (once merged).

**Comment by dbaluta** [comment]
@lgirdwood does integrating our algorithms for decoding compressed audio counts as processing?

**Comment by singalsu** [comment]
@lgirdwood Sure, I'll work with next version after edits by @deb-intel.

**Comment by deb-intel** [comment]
@singalsu @lgirdwood Working on it now. Updates should be published within an hour.

**Comment by deb-intel** [comment]
The table is edited and published.

**Comment by singalsu** [comment]
Thanks @deb-intel !

**Comment by cujomalainey** [comment]
@lgirdwood you want us to update the table with prospective elements?

**Comment by lgirdwood** [comment]
@cujomalainey yes please, we can then link them to features and milestone so it's all publically visible.

**Comment by singalsu** [comment]
What new columns do we need? From previous discussion perhaps "Tuning tool", "Milestone", anything else?

**Pull request merged**
