### PR TITLE
developer_guides: debugability: shell: add usage documentation

### PR DESCRIPTION
**Pull request by kv2019i**
Add basic introduction and usage documentation on how to use Zephyr shell feature with SOF.

### CODE REVIEW

**Comment by kv2019i** [comment]
Keeping as draft until the implementaion PRs get merged.

**Review by lgirdwood — DISMISSED** [review]

**Comment by kv2019i** [comment]
Marking ready for review as the shell backend has been merged in Zephyr and the code has been pulled into SOF main.

**Comment by kv2019i** [comment]
v2:
- missing "-p" in the examples, bug found by @jsarha

**Review by jsarha — APPROVED** [review]
LGTM

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
