### PR TITLE
cmake: arguments

### PR DESCRIPTION
**Pull request by jajanusz**
CMake is mainstream tool, so for now I just describe things specific to our project (Arguments). Later I may add more howtos/best practices in this section.

Signed-off-by: Janusz Jankowski <janusz.jankowski@linux.intel.com>

### CODE REVIEW

**Comment by jajanusz** [comment]
@intelkevinputnam 
Thanks, Good tips. I'll update PR

**Comment by jajanusz** [comment]
Updated

**Comment by jajanusz** [comment]
> Line 6: Since Unit Tests appears as its own header below, either remove the separate header or just make the first one: Firmware.

But first one is for Firmware and Unit tests intentionally - You can say that FW arguments are subset of UT arguments, however Hosts arguments are also different group where FW and UT arguments, make no sense.

I'll be able to make it more clean like FW=generic, UT=ut specific when I'll move host build out of FW build system root.

**Comment by intelkevinputnam** [comment]
@jajanusz OK. No problem. As long as it is intentional. :-)

**Comment by jajanusz** [comment]
@intelkevinputnam Please approve if it's good to merge. Thanks

**Comment by intelkevinputnam** [comment]
@jajanusz Changes are now live at https://thesofproject.github.io Can you do a quick check to make sure everything looks correct?

**Comment by jajanusz** [comment]
> @jajanusz Changes are now live at https://thesofproject.github.io Can you do a quick check to make sure everything looks correct?

looks ok

**Comment by intelkevinputnam** [comment]
@jajanusz Thanks!

**Pull request merged**
