### PR TITLE
VirtIO: add running instructions

### PR DESCRIPTION
**Pull request by lyakh**
This is a brief description of running SOF in a virtual machine.

To be extended and improved as respective repositories merge VirtIO code.

### CODE REVIEW

**Comment by deb-intel** [comment]
@lyakh and @lgirdwood I noticed that these new files have been merged locally to developer_guides/virtualisation. PLEASE NOTE that the virtualisation dir no longer exists since I updated it's spelling to virtualization a few months ago. (Intel's policy is to use the U.S. English spelling.)  I'm not sure how this did not throw an error during the merge process.

**Comment by deb-intel** [comment]
I am making the necessary changes so that the files appear under the correct directories.

**Comment by lgirdwood** [comment]
@deb-intel thanks, strange how it did not flag this.

**Comment by deb-intel** [comment]
@lgirdwood agreed. All PRs have been published. Please review the errors picked up during the publishing process which you can see at https://travis-ci.org/thesofproject/sof-docs. These are sof errors I believe. Thanks.

**Comment by lgirdwood** [comment]
@deb-intel ok, Btw I only checked the CI green tick.

**Pull request merged**
