### PR TITLE
Add sof-eqctl getting started instructions

### PR DESCRIPTION
**Pull request by singalsu**
This patch adds basic usage of the new tool to set up
equalizers during runtime.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
@lgirdwood I'm not able to add reviewers for this PR, please add. Maybe I'm missing rights.

**Comment by singalsu** [comment]
@intelkevinputnam Can you please review this. Thanks!

**Comment by intelkevinputnam** [comment]
Hi @singalsu I'm going to let Deb take a look, as she is the primary reviewer for SOF.

**Comment by deb-intel** [comment]
Hi Seppo. Sorry, I was catching up on editing other files. I will get to yours this week for sure.

**Comment by singalsu** [comment]
OK, thanks!

**Pull request merged**
