### PR TITLE
build: update listings to use smp

### PR DESCRIPTION
**Pull request by jajanusz**
Signed-off-by: Janusz Jankowski <janusz.jankowski@linux.intel.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@xiulipan can you add these SMP configs into CI. Thanks !

**Comment by lgirdwood** [comment]
@xiulipan it's an additional build for platforms > 1 core.

**Comment by jajanusz** [comment]
@lgirdwood  @xiulipan SMP should be default build for all multicore platforms (APL and above), because of having UP as default so far there are some bugs that got unnoticed by CI - like too small memory sections when building for SMP which is our default target for these platforms - https://github.com/thesofproject/sof/pull/455 broke it

I'd wait with adding this to CI until memory section fix is merged (should be today), I can change SMP to be default build in xtensa-build-all.sh when it will be merged

**Comment by jajanusz** [comment]
> As this is some additional build, I think you can have more lines about this.
> Not just some simple replacement.

@xiulipan As i wrote it's not additional build, what you had before can be considered additional build for these platforms, SMP is default for APL+, UP for earlier like BYT ;)

**Comment by xiulipan** [comment]
@jajanusz 
If this is some default change. I think nothing is need for CI.
You need to just change the xtensa-build-all.sh and will enable CI build check.

**Pull request merged**
