### PR TITLE
Convert .travis.yml to github actions

### PR DESCRIPTION
**Pull request by marc-hb**
"deploy" steps not converted yet. I have never seen them run, are they
still in use?

Either way this first and most important part can be merged already.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by paulstelian97 — APPROVED** [review]
Minor comment: In the places where you have multiple steps, they always work in sequence? I don't see any dependencies and I don't yet know if you can have them syntactically.

**Review by xiulipan — APPROVED** [review]
This is exactly same with the Travis jobs, also had some confusing job name like **Supported scripts/requirements.txt** **PIP_IGNORE_INSTALLED=0 requirements-lax.txt**

Also we have a TODO: the deploy part.

PS: what is the LAX means here?

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@marc-hb I assume we should see the Travis "pending" with this PR since it's being moved to GH actions ?

**Comment by marc-hb** [comment]
> Minor comment: In the places where you have multiple steps, they always work in sequence?

Yes: steps are sequential and jobs are concurrent.

> This is exactly same with the Travis jobs, also had some confusing job name like Supported scripts/requirements.txt PIP_IGNORE_INSTALLED=0 requirements-lax.txt
> PS: what is the LAX means here?

The answer to both questions is in the heavily commented `scripts/requirements-lax.txt`

I agree these job names are not great, suggestions welcome... for a future PR? We need this one urgently because:

> @marc-hb I assume we should see the Travis "pending" with this PR since it's being moved to GH actions ?

No, it's just because Travis has been moving most of their systems from travis.org to travis.com to travis.org is overloaded all the time (hence this PR)
https://www.traviscistatus.com/#week

**Comment by marc-hb** [comment]
@deb-intel , @intelkevinputnam , are the "deploy" jobs in .travis.yml still in use?

**Comment by xiulipan** [comment]
@marc-hb We need that job to automatically upload the build result to https://github.com/thesofproject/thesofproject.github.io
As Travis now get delay in job run, it means we will also get delay to auto upload build result to https://github.com/thesofproject/thesofproject.github.io
I believe GitHub action should have better support for such kind of usage? I can have a look first

**Pull request merged**
