### PR TITLE
Algorithms: Add description for SRC component

### PR DESCRIPTION
**Pull request by singalsu**
This patch adds description of algorithm, information how to
customize the rate conversions matrix, customize conversions quality,
and how to test the SRC component.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

### CODE REVIEW

**Comment by singalsu** [comment]
@lgirdwood There's need to fix a bit the testbench if you happen to try this. The described example SRC run does not work since the simplified scheduler has got broken. I need to make a proper fix instead of the hack I'm using ATM. Once fixed it will run again like shown here. Also the new ASRC uses the same testbench and tests as SRC once I have up-streamed the additions.

**Comment by deb-intel** [comment]
@singalsu If you did not create the diagrams in sample_rate_conversion, please include where you got them. Thanks.

**Comment by singalsu** [comment]
> @singalsu If you did not create the diagrams in sample_rate_conversion, please include where you got them. Thanks.

All the images are my own work. I used MS Visio for the signal proc diagrams and the plots were generated by the up-streamed SOF SRC tool. Is png the best format for the diagrams? The appear a bit blurry with a narrow browser window that I typically use but become fully readable if I use more of my 1080p monitor estate.

**Comment by deb-intel** [comment]
@singalsu Thanks for the update! They look fine on my computer but I will let you know for sure after I finish my edits/new PR.

**Pull request merged**
