### PR TITLE
build-guide: build-from-scratch: Use SOF_WORKSPACE throughout the page

### PR DESCRIPTION
**Pull request by ujfalusi**
Use SOF_WORKSPACE consistently throughout the page to make it easier to
follow the instruction if the SOF_WORKSPACE != ~/work/sof

Signed-off-by: Peter Ujfalusi <peter.ujfalusi@gmail.com>

### CODE REVIEW

**Review by dbaluta — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
SOFCI TEST

**Comment by lgirdwood** [comment]
@deb-intel can you check the CI, I'm not sure of the issue

**Comment by deb-intel** [comment]
@lgirdwood Sure. I have not failed those particular checks before . I'll see if @intelkevinputnam can take a look as well.

**Comment by ujfalusi** [comment]
Not sure what is happening, but the error is not related to the patch itself:

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openjdk-lts/openjdk-11-jre-headless_11.0.9.1+1-0ubuntu1~20.04_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
Fetched 17.9 MB in 0s (62.2 MB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openjdk-lts/openjdk-11-jre_11.0.9.1+1-0ubuntu1~20.04_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.

**Comment by marc-hb** [comment]
Explanation and fix in #333, please review.

**Review by marc-hb — APPROVED** [review]

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
I tried to re-run the jobs but this does not get merged with #333. @ujfalusi can you perform a dummy `git commit --amend` to merely change the SHA1 and force push?

**Comment by ujfalusi** [comment]
@marc-hb, now it is passing (/me stating the obvious), thanks!

**Pull request merged**
