### PR TITLE
build: update docker repo into organization

### PR DESCRIPTION
**Pull request by xiulipan**
Use organization instead of personal account.

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

### CODE REVIEW

**Comment by xiulipan** [comment]
@intelkevinputnam 
Are you sure? It seems all "$" characters is added from https://github.com/thesofproject/sof-docs/pull/27/ with f8ee2c40341f393fb119dbbde516c0472d07fa7f

For the output part. I will have a check.

**Comment by lgirdwood** [comment]
@xiulipan yeah, adding $ makes it difficult to copy and paste into the terminal so best to remove.

**Comment by xiulipan** [comment]
@lgirdwood @intelkevinputnam 
OK, I will get all "$" removeonce I got some time.

Should I do it in another PR or just in this PR?

**Comment by lgirdwood** [comment]
@xiulipan another PR for $ removal. Thanks

**Comment by xiulipan** [comment]
@lgirdwood It seems @stripes416 have already done that for me

**Pull request merged**
