### PR TITLE
Add woke test

### PR DESCRIPTION
**Pull request by xiulipan**
Add PR woke checker with reviewdog
preview on https://github.com/xiulipan/sof-docs/pull/2 it will add review comments to GitHub from woke check.

Add manually trigger woke workflow
guide here https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
This will allow you to manually run woke check on existing branch with GitHub Action.

### CODE REVIEW

**Comment by xiulipan** [comment]
Note the manually woke test can only take effect after the PR is merge. Preview on my forked branch
https://github.com/xiulipan/sof-docs/actions?query=workflow%3A%22woke+manually+checker%22

**Comment by xiulipan** [comment]
@deb-intel @lgirdwood It seems we have few existing woke errors

Do we have plan to add some of them into `.wokeignore` or send fix?
image
https://github.com/xiulipan/sof-docs/actions/runs/536200492
```
platforms/intel-cavs/commons/work-queue.rst:47:12: [error] `master` may be insensitive, use `main for firmware-related topics and provider for hardware-related topics` instead
platforms/intel-cavs/commons/work-queue.rst:48:12: [error] `slave` may be insensitive, use `secondary for firmware-related topics and consumer for hardware-related topics` instead
architectures/dsp/intel/cavs-boot/cavs-dsp-boot-overview.rst:129:12: [error] `master` may be insensitive, use `main for firmware-related topics and provider for hardware-related topics` instead
developer_guides/tech/compile_wsl.rst:55:183: [error] `master` may be insensitive, use `main for firmware-related topics and provider for hardware-related topics` instead
getting_started/build-guide/build-from-scratch.rst:75:75: [error] `slave` may be insensitive, use `secondary for firmware-related topics and consumer for hardware-related topics` instead
getting_started/build-guide/build-from-scratch.rst:577:91: [error] `master` may be insensitive, use `main for firmware-related topics and provider for hardware-related topics` instead
developer_guides/firmware/component-tutorial/tut-ii-topology.rst:133:18: [error] `Master` may be insensitive, use `main for firmware-related topics and provider for hardware-related topics` instead
developer_guides/firmware/component-tutorial/tut-ii-topology.rst:182:28: [error] `Master` may be insensitive, use `main for firmware-related topics and provider for hardware-related topics` instead
developer_guides/virtualization/virtualization.rst:134:59: [error] `Master` may be insensitive, use `main for firmware-related topics and provider for hardware-related topics` instead
developer_guides/linux_driver/architecture/sof_driver_arch.rst:318:68: [error] `master` may be insensitive, use `main for firmware-related topics and provider for hardware-related topics` instead
```

**Comment by deb-intel** [comment]
@xiulipan Please do not add them to .wokeignore at this time. I can correct half of the violations immediately so this will give me an opportunity to check out its effectiveness. I planned to ask @lgirdwood about the others which are no big deal. I can add them to .wokeignore later if necessary and if that's cool with you.

Also, please make sure that violations do not cause the merge to fail. Perhaps we can utilize that feature later, but I think it will be an unnecessary headache if we do it now.

Nice work on this, Xiuli!

**Comment by deb-intel** [comment]
@xiulipan I am responding to your statement, "Note the manually woke test can only take effect after the PR is merge. Preview on my forked branch." 

I'm not sure what you are asking. Do we need to make a manual woke test available? This is the workflow as I see it: The user submits a PR. During the check, woke is activated and the the user's file is searched against the customized file, rules-woke.yaml. The violations are listed for the user to see but the request does not fail. Before I or someone else merges the request, we can ask the user to correct the issue.

As an aside: Yesterday I read on Woke's website that we can configure woke to search through only the files in a PR. If I am not mistaken, we have it set up so that woke checks all files (which might be annoying if you see other users' violations). Perhaps we can talk about making them PR-specific in the near future.

**Review by lgirdwood — APPROVED** [review]

**Comment by xiulipan** [comment]
@deb-intel The action workflow "woke PR reviewdog checker" is added for PR by (.github/workflows/woke_pr.yml). https://github.com/thesofproject/sof-docs/actions?query=workflow%3A%22woke+PR+reviewdog+checker%22
But I also added a manually triggered online woke test in (.github/workflows/woke.yml)
So we can try to do some manually overall check later if we update the rules

**Comment by lgirdwood** [comment]
@deb-intel merged and ready for ignore updates. @xiulipan good work !

**Comment by xiulipan** [comment]
@lgirdwood just merged the PR, so I can do a demo here.
This is how we trigger the overall woke check.
image

Please check result in https://github.com/thesofproject/sof-docs/actions/runs/537158476

**Comment by deb-intel** [comment]
@xiulipan I agree with @lgirdwood--good work. You rock!

**Pull request merged**
