### PR TITLE
Reviewed and updated getting started section

### PR DESCRIPTION
**Pull request by intelkevinputnam**
Please DO NOT merge before all reviewers have APPROVED the PR.

@xiulipan please review the changes.

### CODE REVIEW

**Comment by xiulipan** [comment]
@intelkevinputnam 
Get the PR to build a local html version to help review.
It seems a lot of changes are there. I will give feedback while I am reviewing.
Thanks for the fixing.

**Comment by lgirdwood** [comment]
@xiulipan ping. Do you approve

**Comment by xiulipan** [comment]
@lgirdwood 
Busy with the IRQ patches, will have feedback ASAP.

**Comment by xiulipan** [comment]
@intelkevinputnam 
Thanks for helping fix and review the build doc.
The only thing is that we may need some URL update for platform set up guide once @plbossart move the repos into **thesofproject**

@lgirdwood 
This patch LGTM.

**Pull request merged**
