### PR TITLE
Edited Agorithm Spec Info section in algos/index

### PR DESCRIPTION
**Pull request by deb-intel**
Signed-off-by: Deb Taylor <deb.taylor@intel.com>

### CODE REVIEW

**Comment by deb-intel** [comment]
The links listed under "Algorithm Specific Information" did not work. Do they exist or were the links simply a placeholder? In any case, I changed the language for now in order to merge the doc. My apologies if this is incorrect and please feel free to add back the info (or let me know and I will add it back).  Reference PR #158.

**Comment by lgirdwood** [comment]
@deb-intel it's still Work In Progress, @singalsu will be adding the data

**Comment by singalsu** [comment]
Yep, I will start editing/writing rst this week. Sample rate conversion topic could be the first available since I have created the text & figures already. EQ is also in fair shape.

**Comment by deb-intel** [comment]
Sounds good, @singalsu. Thanks for the update.

**Pull request merged**
